export const NOTES = [

  // ── JavaScript ──────────────────────────────────────────────────────────
  {
    id: 1,
    category: "JavaScript",
    subcategory: "Variables",
    title: "Make a variable with const",
    language: "javascript",
    tags: ["javascript", "const", "variable", "basics", "declare"],
    notes: "const makes a variable you will not reassign. This is what you should use most of the time.",
    codeBlock: "const name = 'Jane';\nconst age = 30;\n\nconsole.log(name);\n// Jane",
    notesAfter: "If you try to give it a new value later, JavaScript stops you with an error.",
  },
  {
    id: 2,
    category: "JavaScript",
    subcategory: "Variables",
    title: "Use let when the value changes",
    language: "javascript",
    tags: ["javascript", "let", "variable", "reassign", "basics"],
    notes: "let makes a variable you can give a new value to later. Use it only when you actually need to change the value.",
    codeBlock: "let count = 0;\n\ncount = 1;\ncount = 2;\n\nconsole.log(count);\n// 2",
  },
  {
    id: 3,
    category: "JavaScript",
    subcategory: "Variables",
    title: "const still lets you change an array",
    language: "javascript",
    tags: ["javascript", "const", "array", "mutate", "basics", "gotcha"],
    notes: "const stops you replacing the whole variable. It does not stop you changing what is inside an array or object.",
    codeBlock: "const fruits = ['apple'];\n\nfruits.push('banana');   // allowed\nconsole.log(fruits);\n// ['apple', 'banana']\n\n// fruits = ['cherry'];  // NOT allowed - error",
    notesAfter: "This trips people up. Think of const as locking the label, not the contents.",
  },
  {
    id: 4,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Make a list and read items from it",
    language: "javascript",
    tags: ["javascript", "array", "list", "index", "basics", "read"],
    notes: "An array is a list of values. Each item has a position number called an index. Counting starts at 0, not 1.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nconsole.log(fruits[0]);\n// apple\n\nconsole.log(fruits[2]);\n// cherry\n\nconsole.log(fruits.length);\n// 3",
    notesAfter: "The last item is always at index length - 1. Here that is fruits[2].",
  },
  {
    id: 5,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Add an item to the end with push",
    language: "javascript",
    tags: ["javascript", "array", "push", "add", "append", "basics"],
    notes: "push adds one item to the end of the list. It changes the original array.",
    codeBlock: "const fruits = ['apple', 'banana'];\n\nfruits.push('cherry');\n\nconsole.log(fruits);\n// ['apple', 'banana', 'cherry']",
  },
  {
    id: 6,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Remove the last item with pop",
    language: "javascript",
    tags: ["javascript", "array", "pop", "remove", "delete", "basics"],
    notes: "pop removes the last item and hands it back to you. It changes the original array.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nconst removed = fruits.pop();\n\nconsole.log(removed);\n// cherry\n\nconsole.log(fruits);\n// ['apple', 'banana']",
  },
  {
    id: 7,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Add and remove from the start",
    language: "javascript",
    tags: ["javascript", "array", "unshift", "shift", "start", "front", "basics"],
    notes: "unshift adds to the front. shift removes from the front and hands the item back.",
    codeBlock: "const fruits = ['banana', 'cherry'];\n\nfruits.unshift('apple');\nconsole.log(fruits);\n// ['apple', 'banana', 'cherry']\n\nconst first = fruits.shift();\nconsole.log(first);\n// apple",
    notesAfter: "Easy way to remember: push and pop work on the end, shift and unshift work on the start.",
  },
  {
    id: 8,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Copy a list instead of changing it",
    language: "javascript",
    tags: ["javascript", "array", "spread", "copy", "immutable", "react", "basics"],
    notes: "The three dots (...) copy every item into a new array. The original is left alone. React needs this - it will not notice a change if you edit the old array.",
    codeBlock: "const fruits = ['apple', 'banana'];\n\nconst more = [...fruits, 'cherry'];\n\nconsole.log(more);\n// ['apple', 'banana', 'cherry']\n\nconsole.log(fruits);\n// ['apple', 'banana']   <- unchanged",
    notesAfter: "Use this instead of push whenever the array is in React state.",
  },
  {
    id: 9,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Check if a list contains something",
    language: "javascript",
    tags: ["javascript", "array", "includes", "contains", "check", "basics"],
    notes: "includes asks a yes or no question: is this value in the list?",
    codeBlock: "const fruits = ['apple', 'banana'];\n\nconsole.log(fruits.includes('apple'));\n// true\n\nconsole.log(fruits.includes('cherry'));\n// false",
  },
  {
    id: 10,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Find one item in a list",
    language: "javascript",
    tags: ["javascript", "array", "find", "search", "basics"],
    notes: "find goes through the list and hands back the first item that passes your test. If nothing passes, you get undefined.",
    codeBlock: "const people = [\n  { name: 'Jane', age: 30 },\n  { name: 'Bob', age: 25 },\n];\n\nconst bob = people.find(person => person.name === 'Bob');\n\nconsole.log(bob);\n// { name: 'Bob', age: 25 }",
    notesAfter: "The bit inside the brackets is a small function. It runs once per item and should return true or false.",
  },
  {
    id: 11,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Make a new list from an old one with map",
    language: "javascript",
    tags: ["javascript", "array", "map", "transform", "basics"],
    notes: "map runs your function on every item and collects the results into a new list. The original list is not changed.",
    codeBlock: "const numbers = [1, 2, 3];\n\nconst doubled = numbers.map(number => number * 2);\n\nconsole.log(doubled);\n// [2, 4, 6]\n\nconsole.log(numbers);\n// [1, 2, 3]   <- unchanged",
    notesAfter: "The new list always has the same number of items as the old one.",
  },
  {
    id: 12,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Keep only some items with filter",
    language: "javascript",
    tags: ["javascript", "array", "filter", "remove", "basics"],
    notes: "filter keeps every item where your test returns true, and drops the rest. You get a new list back.",
    codeBlock: "const numbers = [1, 2, 3, 4, 5];\n\nconst big = numbers.filter(number => number > 3);\n\nconsole.log(big);\n// [4, 5]",
    notesAfter: "map changes each item. filter decides which items to keep. They are often used together.",
  },
  {
    id: 13,
    category: "JavaScript",
    subcategory: "Arrays",
    title: "Remove duplicates from a list",
    language: "javascript",
    tags: ["javascript", "array", "set", "unique", "duplicate", "dedupe"],
    notes: "A Set can only hold each value once. Putting a list into a Set and back out again removes the repeats.",
    codeBlock: "const tags = ['react', 'git', 'react', 'css'];\n\nconst unique = [...new Set(tags)];\n\nconsole.log(unique);\n// ['react', 'git', 'css']",
  },
  {
    id: 14,
    category: "JavaScript",
    subcategory: "Loops",
    title: "Loop over a list with for...of",
    language: "javascript",
    tags: ["javascript", "loop", "for", "forof", "iterate", "basics"],
    notes: "A for...of loop runs the code inside once for each item in the list. The name after const is yours to choose - it holds the current item.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nfor (const fruit of fruits) {\n  console.log(fruit);\n}\n\n// apple\n// banana\n// cherry",
    notesAfter: "This is the loop to reach for most of the time. Use it when you just need each item in turn.",
  },
  {
    id: 15,
    category: "JavaScript",
    subcategory: "Loops",
    title: "Loop and get the position too",
    language: "javascript",
    tags: ["javascript", "loop", "foreach", "index", "position", "basics"],
    notes: "forEach gives your function two things: the item, and its position in the list.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nfruits.forEach((fruit, index) => {\n  console.log(index, fruit);\n});\n\n// 0 apple\n// 1 banana\n// 2 cherry",
    notesAfter: "One catch: you cannot stop a forEach early. If you need to break out, use for...of instead.",
  },
  {
    id: 16,
    category: "JavaScript",
    subcategory: "Loops",
    title: "Stop a loop early with break",
    language: "javascript",
    tags: ["javascript", "loop", "break", "stop", "exit", "basics"],
    notes: "break stops the loop straight away. Nothing after it runs, and the loop does not continue to the next item.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nfor (const fruit of fruits) {\n  if (fruit === 'banana') {\n    break;\n  }\n  console.log(fruit);\n}\n\n// apple",
    notesAfter: "Only 'apple' prints. The loop stopped when it reached banana.",
  },
  {
    id: 17,
    category: "JavaScript",
    subcategory: "Loops",
    title: "Skip one item with continue",
    language: "javascript",
    tags: ["javascript", "loop", "continue", "skip", "basics"],
    notes: "continue skips the rest of the code for this item only, then carries on with the next one.",
    codeBlock: "const fruits = ['apple', 'banana', 'cherry'];\n\nfor (const fruit of fruits) {\n  if (fruit === 'banana') {\n    continue;\n  }\n  console.log(fruit);\n}\n\n// apple\n// cherry",
    notesAfter: "banana was skipped, but the loop kept going and still printed cherry.",
  },
  {
    id: 18,
    category: "JavaScript",
    subcategory: "Loops",
    title: "Loop a set number of times",
    language: "javascript",
    tags: ["javascript", "loop", "for", "counter", "times", "basics"],
    notes: "A classic for loop has three parts: where to start, when to keep going, and what to do after each pass.",
    codeBlock: "for (let i = 0; i < 3; i = i + 1) {\n  console.log(i);\n}\n\n// 0\n// 1\n// 2",
    notesAfter: "Read it as: start i at 0, keep going while i is under 3, add 1 each time. You will often see i++ instead of i = i + 1 - they do the same thing.",
  },
  {
    id: 19,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Make an object and read from it",
    language: "javascript",
    tags: ["javascript", "object", "property", "read", "basics"],
    notes: "An object holds named values. You read one with a dot and its name.",
    codeBlock: "const person = {\n  name: 'Jane',\n  age: 30,\n};\n\nconsole.log(person.name);\n// Jane\n\nconsole.log(person.age);\n// 30",
    notesAfter: "Each name is called a key, and each value is called a value. Together they are a property.",
  },
  {
    id: 20,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Add or change a value on an object",
    language: "javascript",
    tags: ["javascript", "object", "add", "update", "property", "basics"],
    notes: "Assign to a name that does not exist yet and it gets added. Assign to one that does and it gets replaced.",
    codeBlock: "const person = { name: 'Jane' };\n\nperson.age = 30;        // added\nperson.name = 'Janet';  // changed\n\nconsole.log(person);\n// { name: 'Janet', age: 30 }",
  },
  {
    id: 21,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Use a variable as the key",
    language: "javascript",
    tags: ["javascript", "object", "bracket", "dynamic", "key", "basics"],
    notes: "Square brackets let you look up a key whose name is held in a variable. A dot cannot do this.",
    codeBlock: "const person = { name: 'Jane', age: 30 };\n\nconst whichKey = 'name';\n\nconsole.log(person[whichKey]);\n// Jane",
    notesAfter: "This is how form handlers update the right field: form[event.target.name] = value.",
  },
  {
    id: 22,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Copy an object with a change",
    language: "javascript",
    tags: ["javascript", "object", "spread", "copy", "update", "react", "basics"],
    notes: "The three dots copy every property into a new object. Anything you write after overwrites what was copied.",
    codeBlock: "const person = { name: 'Jane', age: 30 };\n\nconst older = { ...person, age: 31 };\n\nconsole.log(older);\n// { name: 'Jane', age: 31 }\n\nconsole.log(person);\n// { name: 'Jane', age: 30 }   <- unchanged",
    notesAfter: "This is the standard way to update React state without touching the original.",
  },
  {
    id: 23,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Pull values out with destructuring",
    language: "javascript",
    tags: ["javascript", "destructuring", "object", "unpack", "basics"],
    notes: "Destructuring takes properties out of an object and makes them into their own variables. The names on the left must match the keys.",
    codeBlock: "const person = { name: 'Jane', age: 30 };\n\nconst { name, age } = person;\n\nconsole.log(name);\n// Jane\n\nconsole.log(age);\n// 30",
    notesAfter: "This is the same as writing const name = person.name; const age = person.age; just shorter.",
  },
  {
    id: 24,
    category: "JavaScript",
    subcategory: "Objects",
    title: "Loop over an object",
    language: "javascript",
    tags: ["javascript", "object", "entries", "loop", "iterate", "basics"],
    notes: "Object.entries turns an object into a list of [key, value] pairs, which you can then loop over.",
    codeBlock: "const person = { name: 'Jane', age: 30 };\n\nfor (const [key, value] of Object.entries(person)) {\n  console.log(key, value);\n}\n\n// name Jane\n// age 30",
    notesAfter: "Object.keys gives you just the names, and Object.values gives you just the values.",
  },
  {
    id: 25,
    category: "JavaScript",
    subcategory: "Functions",
    title: "Write a function",
    language: "javascript",
    tags: ["javascript", "function", "return", "parameter", "basics"],
    notes: "A function is a named block of code you can run whenever you want. Values you pass in are called arguments.",
    codeBlock: "function add(a, b) {\n  return a + b;\n}\n\nconst total = add(2, 3);\n\nconsole.log(total);\n// 5",
    notesAfter: "Without return, the function hands back undefined.",
  },
  {
    id: 26,
    category: "JavaScript",
    subcategory: "Functions",
    title: "Write a function as an arrow",
    language: "javascript",
    tags: ["javascript", "function", "arrow", "shorthand", "basics"],
    notes: "An arrow function does the same job with shorter syntax. These two are the same.",
    codeBlock: "function addLong(a, b) {\n  return a + b;\n}\n\nconst addShort = (a, b) => {\n  return a + b;\n};\n\nconsole.log(addShort(2, 3));\n// 5",
  },
  {
    id: 27,
    category: "JavaScript",
    subcategory: "Functions",
    title: "Arrow functions can skip the return",
    language: "javascript",
    tags: ["javascript", "function", "arrow", "implicit return", "basics", "gotcha"],
    notes: "If an arrow function has no curly braces, it returns its one line automatically.",
    codeBlock: "const double = (n) => n * 2;\n\nconsole.log(double(5));\n// 10\n\n// with braces you must write return yourself\nconst alsoDouble = (n) => {\n  return n * 2;\n};",
    notesAfter: "Watch out: (n) => { n * 2 } returns undefined. The braces mean you have to say return.",
  },
  {
    id: 28,
    category: "JavaScript",
    subcategory: "Functions",
    title: "Give a parameter a default value",
    language: "javascript",
    tags: ["javascript", "function", "default", "parameter", "basics"],
    notes: "A default is used when the caller leaves that argument out.",
    codeBlock: "function greet(name = 'there') {\n  return 'Hi ' + name;\n}\n\nconsole.log(greet('Jane'));\n// Hi Jane\n\nconsole.log(greet());\n// Hi there",
  },
  {
    id: 29,
    category: "JavaScript",
    subcategory: "Conditionals",
    title: "Run code only if something is true",
    language: "javascript",
    tags: ["javascript", "if", "else", "condition", "basics"],
    notes: "An if statement runs its block only when the test is true. else covers every other case.",
    codeBlock: "const age = 20;\n\nif (age >= 18) {\n  console.log('Adult');\n} else {\n  console.log('Child');\n}\n\n// Adult",
  },
  {
    id: 30,
    category: "JavaScript",
    subcategory: "Conditionals",
    title: "Always compare with three equals",
    language: "javascript",
    tags: ["javascript", "equality", "comparison", "strict", "basics", "gotcha"],
    notes: "=== checks the value and the type. == tries to convert things first and gives confusing answers. Use === every time.",
    codeBlock: "console.log(1 === 1);\n// true\n\nconsole.log(1 === '1');\n// false   <- number is not a string\n\nconsole.log(1 == '1');\n// true    <- confusing, avoid ==",
  },
  {
    id: 31,
    category: "JavaScript",
    subcategory: "Conditionals",
    title: "Values that count as false",
    language: "javascript",
    tags: ["javascript", "truthy", "falsy", "boolean", "basics"],
    notes: "Only six values are treated as false: false, 0, empty string, null, undefined and NaN. Everything else counts as true.",
    codeBlock: "if ('') {\n  console.log('never runs');\n}\n\nif ('hello') {\n  console.log('runs');\n}\n\n// runs",
    notesAfter: "Careful: an empty array [] and an empty object {} both count as TRUE. Check array.length instead.",
  },
  {
    id: 32,
    category: "JavaScript",
    subcategory: "Conditionals",
    title: "Pick between two values in one line",
    language: "javascript",
    tags: ["javascript", "ternary", "condition", "inline", "basics"],
    notes: "A question mark picks between two values based on a test. Read it as: if this, then that, otherwise the other.",
    codeBlock: "const count = 3;\n\nconst label = count === 1 ? 'note' : 'notes';\n\nconsole.log(label);\n// notes",
    notesAfter: "Handy inside JSX, where a full if statement will not fit.",
  },
  {
    id: 33,
    category: "JavaScript",
    subcategory: "Strings",
    title: "Put a variable inside a string",
    language: "javascript",
    tags: ["javascript", "string", "template literal", "interpolation", "basics"],
    notes: "Wrap the string in backticks and put variables inside ${ }. Much easier to read than joining strings with +.",
    codeBlock: "const name = 'Jane';\nconst count = 3;\n\nconsole.log(`${name} has ${count} notes`);\n// Jane has 3 notes",
    notesAfter: "The backtick key is usually above Tab, to the left of the number 1.",
  },
  {
    id: 34,
    category: "JavaScript",
    subcategory: "Strings",
    title: "Clean up and change text",
    language: "javascript",
    tags: ["javascript", "string", "trim", "lowercase", "replace", "basics"],
    notes: "String methods always hand back a new string. The original is never changed.",
    codeBlock: "const messy = '  Hello World  ';\n\nconsole.log(messy.trim());\n// Hello World\n\nconsole.log(messy.toLowerCase());\n//   hello world\n\nconsole.log('cat'.replace('c', 'b'));\n// bat",
  },
  {
    id: 35,
    category: "JavaScript",
    subcategory: "Strings",
    title: "Split text into a list",
    language: "javascript",
    tags: ["javascript", "string", "split", "join", "array", "basics"],
    notes: "split cuts a string wherever it finds the character you give it. join does the reverse.",
    codeBlock: "const tags = 'git, react, css';\n\nconst list = tags.split(', ');\nconsole.log(list);\n// ['git', 'react', 'css']\n\nconsole.log(list.join(' | '));\n// git | react | css",
  },
  {
    id: 36,
    category: "JavaScript",
    subcategory: "Async",
    title: "Wait for something slow with await",
    language: "javascript",
    tags: ["javascript", "async", "await", "promise", "fetch", "basics"],
    notes: "Some jobs take time, like asking a server for data. await pauses until the answer arrives. A function using await must be marked async.",
    codeBlock: "async function loadNotes() {\n  const response = await fetch('/api/notes');\n  const data = await response.json();\n\n  console.log(data);\n}\n\nloadNotes();",
    notesAfter: "Without await you get a Promise object instead of your data - a very common confusion.",
  },
  {
    id: 37,
    category: "JavaScript",
    subcategory: "Async",
    title: "Handle an error from await",
    language: "javascript",
    tags: ["javascript", "async", "try catch", "error", "basics"],
    notes: "If something goes wrong inside await, it throws an error. try/catch stops that error crashing your app.",
    codeBlock: "async function loadNotes() {\n  try {\n    const response = await fetch('/api/notes');\n    return await response.json();\n  } catch (error) {\n    console.log('Something went wrong:', error.message);\n  }\n}",
    notesAfter: "The catch block only runs when there is a problem. Normal runs skip it entirely.",
  },
  {
    id: 38,
    category: "JavaScript",
    subcategory: "Async",
    title: "Check the response worked",
    language: "javascript",
    tags: ["javascript", "fetch", "response", "ok", "status", "error"],
    notes: "fetch does not throw an error for a 404 or 500. You have to check response.ok yourself.",
    codeBlock: "const response = await fetch('/api/notes');\n\nif (!response.ok) {\n  throw new Error('Request failed: ' + response.status);\n}\n\nconst data = await response.json();",
    notesAfter: "Without this check, a server error page gets passed to response.json() and you see a confusing JSON parse error instead.",
  },
  {
    id: 39,
    category: "JavaScript",
    subcategory: "Types",
    title: "Turn text into a number",
    language: "javascript",
    tags: ["javascript", "number", "convert", "parseint", "basics"],
    notes: "Values from input boxes are always text, even when they look like numbers. Number() converts them.",
    codeBlock: "const typed = '42';\n\nconsole.log(typed + 1);\n// 421   <- joined as text\n\nconsole.log(Number(typed) + 1);\n// 43    <- added as numbers",
    notesAfter: "This is why a form that adds numbers sometimes glues them together instead.",
  },
  {
    id: 40,
    category: "JavaScript",
    subcategory: "Types",
    title: "Check what type something is",
    language: "javascript",
    tags: ["javascript", "typeof", "type", "check", "array", "basics"],
    notes: "typeof tells you what kind of value you have. Arrays are the odd one out - use Array.isArray for those.",
    codeBlock: "console.log(typeof 'hello');\n// string\n\nconsole.log(typeof 42);\n// number\n\nconsole.log(typeof [1, 2]);\n// object   <- not helpful\n\nconsole.log(Array.isArray([1, 2]));\n// true",
  },
  {
    id: 41,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Save and read a value",
    language: "javascript",
    tags: ["javascript", "localstorage", "storage", "save", "browser", "basics"],
    notes: "localStorage keeps a value in the browser, even after the page is closed and reopened. You give it a name and a value.",
    codeBlock: "localStorage.setItem('username', 'Jane');\n\nconst name = localStorage.getItem('username');\n\nconsole.log(name);\n// Jane",
    notesAfter: "The name is called a key. Pick something specific like 'myapp-username' so it does not clash with other code.",
  },
  {
    id: 42,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Everything is saved as text",
    language: "javascript",
    tags: ["javascript", "localstorage", "string", "number", "type", "gotcha"],
    notes: "localStorage only holds strings. Save a number and you get a string back.",
    codeBlock: "localStorage.setItem('count', 5);\n\nconst count = localStorage.getItem('count');\n\nconsole.log(count);\n// 5\n\nconsole.log(typeof count);\n// string",
    notesAfter: "This is why count + 1 gives you '51' instead of 6. Wrap it in Number() first.",
  },
  {
    id: 43,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Save a list or an object",
    language: "javascript",
    tags: ["javascript", "localstorage", "json", "stringify", "parse", "object", "array"],
    notes: "Since only text can be stored, turn your data into text with JSON.stringify on the way in, and back again with JSON.parse on the way out.",
    codeBlock: "const tags = ['git', 'react'];\n\nlocalStorage.setItem('tags', JSON.stringify(tags));\n\nconst saved = JSON.parse(localStorage.getItem('tags'));\n\nconsole.log(saved);\n// ['git', 'react']",
    notesAfter: "Forget stringify and you save the text '[object Object]', which is useless when you read it back.",
  },
  {
    id: 44,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Handle a missing value",
    language: "javascript",
    tags: ["javascript", "localstorage", "null", "default", "missing", "gotcha"],
    notes: "getItem hands back null when the key was never saved. Check for it before using the value.",
    codeBlock: "const saved = localStorage.getItem('tags');\n\nconst tags = saved ? JSON.parse(saved) : [];\n\nconsole.log(tags);\n// []",
    notesAfter: "Calling JSON.parse(null) does not crash, but JSON.parse of a half-written value does. The check above avoids both.",
  },
  {
    id: 45,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Remove saved values",
    language: "javascript",
    tags: ["javascript", "localstorage", "remove", "clear", "delete"],
    notes: "removeItem deletes one key. clear wipes everything your site has saved.",
    codeBlock: "localStorage.removeItem('username');\n\nlocalStorage.clear();",
    notesAfter: "clear only affects your own site. It cannot touch data saved by other websites.",
  },
  {
    id: 46,
    category: "JavaScript",
    subcategory: "Storage",
    title: "Guard against storage being blocked",
    language: "javascript",
    tags: ["javascript", "localstorage", "try catch", "private", "error", "safe"],
    notes: "Private browsing and some browser settings make localStorage throw an error. Wrap it so your app keeps working.",
    codeBlock: "function readTags() {\n  try {\n    const saved = localStorage.getItem('tags');\n    return saved ? JSON.parse(saved) : [];\n  } catch {\n    return [];\n  }\n}",
    notesAfter: "Worth doing for anything a user would be annoyed to lose. For a small preference, plain getItem is usually fine.",
  },
  {
    id: 47,
    category: "JavaScript",
    subcategory: "Storage",
    title: "localStorage versus sessionStorage",
    language: "javascript",
    tags: ["javascript", "localstorage", "sessionstorage", "session", "difference"],
    notes: "They work identically. The only difference is how long the data lasts.",
    codeBlock: "// stays until you delete it\nlocalStorage.setItem('theme', 'dark');\n\n// disappears when the tab is closed\nsessionStorage.setItem('draft', 'unsaved text');",
    notesAfter: "Use sessionStorage for things that should not outlive the visit, like a half-filled form.",
  },

  // ── Python ──────────────────────────────────────────────────────────────
  {
    id: 48,
    category: "Python",
    subcategory: "Variables",
    title: "Make a variable",
    language: "python",
    tags: ["python", "variable", "assign", "basics"],
    notes: "Python has no const or let. You just give a name a value.",
    codeBlock: "name = 'Jane'\nage = 30\n\nprint(name)\n# Jane",
    notesAfter: "Names are usually written in lower_case_with_underscores, not camelCase like JavaScript.",
  },
  {
    id: 49,
    category: "Python",
    subcategory: "Variables",
    title: "Swap two variables",
    language: "python",
    tags: ["python", "variable", "swap", "tuple", "basics"],
    notes: "Python lets you assign two things at once, so swapping needs no temporary variable.",
    codeBlock: "a = 1\nb = 2\n\na, b = b, a\n\nprint(a, b)\n# 2 1",
  },
  {
    id: 50,
    category: "Python",
    subcategory: "Variables",
    title: "Print several things at once",
    language: "python",
    tags: ["python", "print", "output", "console", "basics"],
    notes: "print takes as many values as you like and puts a space between them.",
    codeBlock: "name = 'Jane'\nage = 30\n\nprint(name, age)\n# Jane 30",
    notesAfter: "In JavaScript you would write console.log. In Python it is just print.",
  },
  {
    id: 51,
    category: "Python",
    subcategory: "Lists",
    title: "Make a list and read from it",
    language: "python",
    tags: ["python", "list", "index", "read", "basics"],
    notes: "A list holds values in order. Positions start at 0.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nprint(fruits[0])\n# apple\n\nprint(len(fruits))\n# 3",
    notesAfter: "len() gives the length. In JavaScript it would be fruits.length.",
  },
  {
    id: 52,
    category: "Python",
    subcategory: "Lists",
    title: "Count backwards from the end",
    language: "python",
    tags: ["python", "list", "negative", "index", "last", "basics"],
    notes: "A negative index counts from the end. -1 is the last item.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nprint(fruits[-1])\n# cherry\n\nprint(fruits[-2])\n# banana",
    notesAfter: "This is much neater than JavaScript, where you need fruits[fruits.length - 1].",
  },
  {
    id: 53,
    category: "Python",
    subcategory: "Lists",
    title: "Add an item to a list",
    language: "python",
    tags: ["python", "list", "append", "add", "basics"],
    notes: "append adds one item to the end.",
    codeBlock: "fruits = ['apple', 'banana']\n\nfruits.append('cherry')\n\nprint(fruits)\n# ['apple', 'banana', 'cherry']",
    notesAfter: "This is Python's version of push.",
  },
  {
    id: 54,
    category: "Python",
    subcategory: "Lists",
    title: "Remove an item from a list",
    language: "python",
    tags: ["python", "list", "remove", "pop", "delete", "basics"],
    notes: "remove deletes by value. pop deletes by position and hands the item back.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nfruits.remove('banana')\nprint(fruits)\n# ['apple', 'cherry']\n\nlast = fruits.pop()\nprint(last)\n# cherry",
    notesAfter: "pop() with no number takes the last item. pop(0) takes the first.",
  },
  {
    id: 55,
    category: "Python",
    subcategory: "Lists",
    title: "Take a slice of a list",
    language: "python",
    tags: ["python", "list", "slice", "range", "basics"],
    notes: "Two numbers in square brackets give you a section. The first is where to start, the second is where to stop before.",
    codeBlock: "numbers = [10, 20, 30, 40, 50]\n\nprint(numbers[1:3])\n# [20, 30]\n\nprint(numbers[:2])\n# [10, 20]\n\nprint(numbers[2:])\n# [30, 40, 50]",
    notesAfter: "The end number is not included. numbers[1:3] gives positions 1 and 2, not 3.",
  },
  {
    id: 56,
    category: "Python",
    subcategory: "Lists",
    title: "Check if something is in a list",
    language: "python",
    tags: ["python", "list", "in", "contains", "check", "basics"],
    notes: "The word 'in' asks whether a value is in the list.",
    codeBlock: "fruits = ['apple', 'banana']\n\nprint('apple' in fruits)\n# True\n\nprint('cherry' in fruits)\n# False",
    notesAfter: "True and False start with capital letters in Python.",
  },
  {
    id: 57,
    category: "Python",
    subcategory: "Lists",
    title: "Sort a list",
    language: "python",
    tags: ["python", "list", "sort", "sorted", "order", "basics"],
    notes: "sort() changes the list itself. sorted() leaves it alone and hands back a new one.",
    codeBlock: "numbers = [3, 1, 2]\n\nnumbers.sort()\nprint(numbers)\n# [1, 2, 3]\n\nwords = ['c', 'a', 'b']\nprint(sorted(words))\n# ['a', 'b', 'c']",
  },
  {
    id: 58,
    category: "Python",
    subcategory: "Lists",
    title: "Build a list in one line",
    language: "python",
    tags: ["python", "comprehension", "list", "basics"],
    notes: "A list comprehension makes a new list from an old one. Read it as: give me this, for each item.",
    codeBlock: "numbers = [1, 2, 3]\n\ndoubled = [n * 2 for n in numbers]\n\nprint(doubled)\n# [2, 4, 6]",
    notesAfter: "This is Python's version of map. It is used constantly, so it is worth getting comfortable with.",
  },
  {
    id: 59,
    category: "Python",
    subcategory: "Lists",
    title: "Filter while you build a list",
    language: "python",
    tags: ["python", "comprehension", "filter", "if", "basics"],
    notes: "Put an if on the end and only matching items are kept.",
    codeBlock: "numbers = [1, 2, 3, 4, 5]\n\nbig = [n for n in numbers if n > 3]\n\nprint(big)\n# [4, 5]",
    notesAfter: "This does the same job as filter in JavaScript.",
  },
  {
    id: 60,
    category: "Python",
    subcategory: "Loops",
    title: "Loop over a list",
    language: "python",
    tags: ["python", "loop", "for", "iterate", "basics"],
    notes: "A for loop runs the indented code once for each item. The name after 'for' is yours to choose.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nfor fruit in fruits:\n    print(fruit)\n\n# apple\n# banana\n# cherry",
    notesAfter: "The colon and the indent are how Python knows what belongs to the loop. Missing either is an error.",
  },
  {
    id: 61,
    category: "Python",
    subcategory: "Loops",
    title: "Loop and get the position too",
    language: "python",
    tags: ["python", "loop", "enumerate", "index", "position", "basics"],
    notes: "enumerate hands you the position and the item together.",
    codeBlock: "fruits = ['apple', 'banana']\n\nfor index, fruit in enumerate(fruits):\n    print(index, fruit)\n\n# 0 apple\n# 1 banana",
    notesAfter: "Do not loop over range(len(fruits)) to get positions. enumerate is the Python way.",
  },
  {
    id: 62,
    category: "Python",
    subcategory: "Loops",
    title: "Loop a set number of times",
    language: "python",
    tags: ["python", "loop", "range", "counter", "times", "basics"],
    notes: "range(3) counts 0, 1, 2. It stops before the number you give it.",
    codeBlock: "for i in range(3):\n    print(i)\n\n# 0\n# 1\n# 2",
    notesAfter: "range(1, 4) starts at 1 and stops before 4, giving 1, 2, 3.",
  },
  {
    id: 63,
    category: "Python",
    subcategory: "Loops",
    title: "Stop a loop early",
    language: "python",
    tags: ["python", "loop", "break", "stop", "basics"],
    notes: "break leaves the loop straight away.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nfor fruit in fruits:\n    if fruit == 'banana':\n        break\n    print(fruit)\n\n# apple",
    notesAfter: "Only apple prints. The loop stopped at banana.",
  },
  {
    id: 64,
    category: "Python",
    subcategory: "Loops",
    title: "Skip one item",
    language: "python",
    tags: ["python", "loop", "continue", "skip", "basics"],
    notes: "continue skips the rest of this pass and moves to the next item.",
    codeBlock: "fruits = ['apple', 'banana', 'cherry']\n\nfor fruit in fruits:\n    if fruit == 'banana':\n        continue\n    print(fruit)\n\n# apple\n# cherry",
  },
  {
    id: 65,
    category: "Python",
    subcategory: "Loops",
    title: "Repeat while something is true",
    language: "python",
    tags: ["python", "while", "loop", "condition", "basics"],
    notes: "A while loop keeps going until its test becomes false.",
    codeBlock: "count = 0\n\nwhile count < 3:\n    print(count)\n    count = count + 1\n\n# 0\n# 1\n# 2",
    notesAfter: "Make sure something inside the loop changes the test, or it will run forever.",
  },
  {
    id: 66,
    category: "Python",
    subcategory: "Dictionaries",
    title: "Make a dictionary and read from it",
    language: "python",
    tags: ["python", "dict", "dictionary", "key", "basics"],
    notes: "A dictionary holds named values. Square brackets read one by name.",
    codeBlock: "person = {'name': 'Jane', 'age': 30}\n\nprint(person['name'])\n# Jane",
    notesAfter: "This is Python's version of a JavaScript object. Note the keys are in quotes.",
  },
  {
    id: 67,
    category: "Python",
    subcategory: "Dictionaries",
    title: "Read a key safely",
    language: "python",
    tags: ["python", "dict", "get", "default", "missing", "basics"],
    notes: "Square brackets crash if the key is missing. get hands back None instead, or a fallback you choose.",
    codeBlock: "person = {'name': 'Jane'}\n\nprint(person.get('age'))\n# None\n\nprint(person.get('age', 0))\n# 0",
    notesAfter: "Use get whenever you are not certain the key is there.",
  },
  {
    id: 68,
    category: "Python",
    subcategory: "Dictionaries",
    title: "Add or change a value",
    language: "python",
    tags: ["python", "dict", "add", "update", "basics"],
    notes: "Assign to a key and it is added if new, or replaced if it already exists.",
    codeBlock: "person = {'name': 'Jane'}\n\nperson['age'] = 30\n\nprint(person)\n# {'name': 'Jane', 'age': 30}",
  },
  {
    id: 69,
    category: "Python",
    subcategory: "Dictionaries",
    title: "Loop over a dictionary",
    language: "python",
    tags: ["python", "dict", "items", "loop", "iterate", "basics"],
    notes: "items() gives you the key and the value together.",
    codeBlock: "person = {'name': 'Jane', 'age': 30}\n\nfor key, value in person.items():\n    print(key, value)\n\n# name Jane\n# age 30",
    notesAfter: "keys() gives just the names and values() gives just the values.",
  },
  {
    id: 70,
    category: "Python",
    subcategory: "Dictionaries",
    title: "Check if a key exists",
    language: "python",
    tags: ["python", "dict", "in", "check", "key", "basics"],
    notes: "'in' checks the keys, not the values.",
    codeBlock: "person = {'name': 'Jane'}\n\nprint('name' in person)\n# True\n\nprint('Jane' in person)\n# False",
  },
  {
    id: 71,
    category: "Python",
    subcategory: "Strings",
    title: "Put a variable inside a string",
    language: "python",
    tags: ["python", "fstring", "format", "string", "basics"],
    notes: "Put an f before the quotes, then use curly braces to drop values in.",
    codeBlock: "name = 'Jane'\ncount = 3\n\nprint(f'{name} has {count} notes')\n# Jane has 3 notes",
    notesAfter: "Forgetting the f is a common slip. Without it you get the braces printed literally.",
  },
  {
    id: 72,
    category: "Python",
    subcategory: "Strings",
    title: "Clean up text",
    language: "python",
    tags: ["python", "string", "strip", "lower", "upper", "basics"],
    notes: "String methods hand back a new string. The original never changes.",
    codeBlock: "messy = '  Hello  '\n\nprint(messy.strip())\n# Hello\n\nprint('HELLO'.lower())\n# hello",
    notesAfter: "strip() is Python's trim().",
  },
  {
    id: 73,
    category: "Python",
    subcategory: "Strings",
    title: "Split text into a list",
    language: "python",
    tags: ["python", "string", "split", "join", "basics"],
    notes: "split cuts a string into a list. join puts a list back into a string.",
    codeBlock: "tags = 'git, react, css'\n\nparts = tags.split(', ')\nprint(parts)\n# ['git', 'react', 'css']\n\nprint(' | '.join(parts))\n# git | react | css",
    notesAfter: "join is written backwards from what you might expect: the separator comes first.",
  },
  {
    id: 74,
    category: "Python",
    subcategory: "Strings",
    title: "Check what text starts with or contains",
    language: "python",
    tags: ["python", "string", "startswith", "in", "check", "basics"],
    notes: "'in' works on strings too, and checks for a section of text.",
    codeBlock: "title = 'Python basics'\n\nprint('basics' in title)\n# True\n\nprint(title.startswith('Python'))\n# True",
  },
  {
    id: 75,
    category: "Python",
    subcategory: "Functions",
    title: "Write a function",
    language: "python",
    tags: ["python", "function", "def", "return", "basics"],
    notes: "def starts a function. The indented lines are its body. return hands a value back.",
    codeBlock: "def add(a, b):\n    return a + b\n\ntotal = add(2, 3)\n\nprint(total)\n# 5",
    notesAfter: "Without return, the function hands back None.",
  },
  {
    id: 76,
    category: "Python",
    subcategory: "Functions",
    title: "Give a parameter a default",
    language: "python",
    tags: ["python", "function", "default", "parameter", "basics"],
    notes: "A default is used when the caller leaves that argument out.",
    codeBlock: "def greet(name='there'):\n    return 'Hi ' + name\n\nprint(greet('Jane'))\n# Hi Jane\n\nprint(greet())\n# Hi there",
  },
  {
    id: 77,
    category: "Python",
    subcategory: "Functions",
    title: "Name your arguments when calling",
    language: "python",
    tags: ["python", "function", "keyword", "argument", "basics"],
    notes: "You can pass arguments by name, in any order. It makes the call much easier to read.",
    codeBlock: "def make_note(title, category, pinned=False):\n    return {'title': title, 'category': category, 'pinned': pinned}\n\nnote = make_note(title='Hello', category='Python', pinned=True)\n\nprint(note['pinned'])\n# True",
    notesAfter: "Very common in Django and other libraries, where functions take many options.",
  },
  {
    id: 78,
    category: "Python",
    subcategory: "Functions",
    title: "Return more than one value",
    language: "python",
    tags: ["python", "function", "tuple", "return", "multiple", "basics"],
    notes: "Separate values with commas and Python bundles them together. Unpack them the same way.",
    codeBlock: "def get_size():\n    return 800, 600\n\nwidth, height = get_size()\n\nprint(width, height)\n# 800 600",
  },
  {
    id: 79,
    category: "Python",
    subcategory: "Conditionals",
    title: "Run code only if something is true",
    language: "python",
    tags: ["python", "if", "else", "elif", "condition", "basics"],
    notes: "if runs its block when the test is true. elif checks another case, else covers the rest.",
    codeBlock: "age = 20\n\nif age >= 18:\n    print('Adult')\nelif age >= 13:\n    print('Teen')\nelse:\n    print('Child')\n\n# Adult",
    notesAfter: "elif is short for 'else if'. Python does not have a switch statement.",
  },
  {
    id: 80,
    category: "Python",
    subcategory: "Conditionals",
    title: "Combine conditions",
    language: "python",
    tags: ["python", "and", "or", "not", "condition", "basics"],
    notes: "Python uses the words and, or and not instead of symbols.",
    codeBlock: "age = 20\nmember = True\n\nif age >= 18 and member:\n    print('Allowed')\n\n# Allowed",
    notesAfter: "In JavaScript these would be &&, || and !.",
  },
  {
    id: 81,
    category: "Python",
    subcategory: "Conditionals",
    title: "Values that count as false",
    language: "python",
    tags: ["python", "truthy", "falsy", "empty", "basics"],
    notes: "Empty things count as false: 0, empty string, empty list, empty dict, and None. Everything else is true.",
    codeBlock: "items = []\n\nif items:\n    print('has items')\nelse:\n    print('empty')\n\n# empty",
    notesAfter: "This is different from JavaScript, where an empty array counts as TRUE.",
  },
  {
    id: 82,
    category: "Python",
    subcategory: "Conditionals",
    title: "Check for nothing with None",
    language: "python",
    tags: ["python", "none", "null", "is", "check", "basics"],
    notes: "None is Python's version of null. Compare it with 'is', not '=='.",
    codeBlock: "value = None\n\nif value is None:\n    print('nothing here')\n\n# nothing here",
    notesAfter: "'is' checks it is the exact same object, which is the correct test for None.",
  },
  {
    id: 83,
    category: "Python",
    subcategory: "Conditionals",
    title: "Pick between two values in one line",
    language: "python",
    tags: ["python", "ternary", "inline", "condition", "basics"],
    notes: "Python writes this in a readable order: the value, then the test, then the fallback.",
    codeBlock: "count = 3\n\nlabel = 'note' if count == 1 else 'notes'\n\nprint(label)\n# notes",
  },
  {
    id: 84,
    category: "Python",
    subcategory: "Types",
    title: "Turn text into a number",
    language: "python",
    tags: ["python", "int", "float", "convert", "type", "basics"],
    notes: "Input from a user is always text. int() and float() convert it.",
    codeBlock: "typed = '42'\n\nprint(typed + '1')\n# 421   <- joined as text\n\nprint(int(typed) + 1)\n# 43    <- added as numbers",
    notesAfter: "int('42px') raises an error, unlike JavaScript's parseInt which would give 42.",
  },
  {
    id: 85,
    category: "Python",
    subcategory: "Types",
    title: "Check what type something is",
    language: "python",
    tags: ["python", "type", "isinstance", "check", "basics"],
    notes: "type() tells you what something is. isinstance() asks a yes or no question.",
    codeBlock: "print(type('hello'))\n# <class 'str'>\n\nprint(isinstance(42, int))\n# True",
  },
  {
    id: 86,
    category: "Python",
    subcategory: "Types",
    title: "Two kinds of division",
    language: "python",
    tags: ["python", "division", "integer", "float", "math", "basics"],
    notes: "A single slash always gives a decimal. A double slash throws away the remainder.",
    codeBlock: "print(7 / 2)\n# 3.5\n\nprint(7 // 2)\n# 3\n\nprint(7 % 2)\n# 1   <- the remainder",
  },
  {
    id: 87,
    category: "Python",
    subcategory: "Files",
    title: "Read a file",
    language: "python",
    tags: ["python", "file", "read", "open", "with", "basics"],
    notes: "'with' opens the file and closes it again automatically when the block ends.",
    codeBlock: "with open('notes.txt') as file:\n    content = file.read()\n\nprint(content)",
    notesAfter: "Always use 'with'. Without it, you have to remember to close the file yourself.",
  },
  {
    id: 88,
    category: "Python",
    subcategory: "Files",
    title: "Write to a file",
    language: "python",
    tags: ["python", "file", "write", "open", "basics"],
    notes: "The 'w' means write. It replaces whatever was in the file before.",
    codeBlock: "with open('notes.txt', 'w') as file:\n    file.write('Hello')",
    notesAfter: "Use 'a' instead of 'w' to add to the end rather than replacing.",
  },
  {
    id: 89,
    category: "Python",
    subcategory: "Files",
    title: "Read and write JSON",
    language: "python",
    tags: ["python", "json", "file", "load", "dump", "basics"],
    notes: "json.load reads a file into Python data. json.dump writes Python data back out.",
    codeBlock: "import json\n\nwith open('notes.json') as file:\n    notes = json.load(file)\n\nwith open('notes.json', 'w') as file:\n    json.dump(notes, file, indent=2)",
    notesAfter: "indent=2 makes the saved file readable instead of one long line.",
  },
  {
    id: 90,
    category: "Python",
    subcategory: "Errors",
    title: "Handle an error without crashing",
    language: "python",
    tags: ["python", "try", "except", "error", "exception", "basics"],
    notes: "try runs your code. If it fails, except catches the problem instead of stopping the program.",
    codeBlock: "try:\n    number = int('not a number')\nexcept ValueError:\n    print('That was not a number')\n\n# That was not a number",
    notesAfter: "Name the specific error you expect. A bare 'except' hides bugs you did want to know about.",
  },
  {
    id: 91,
    category: "Python",
    subcategory: "Errors",
    title: "Raise your own error",
    language: "python",
    tags: ["python", "raise", "error", "exception", "validation", "basics"],
    notes: "raise stops the function and reports a problem to whoever called it.",
    codeBlock: "def set_age(age):\n    if age < 0:\n        raise ValueError('Age cannot be negative')\n    return age",
  },

  // ── React ───────────────────────────────────────────────────────────────
  {
    id: 92,
    category: "React",
    subcategory: "Components",
    title: "Write a component",
    language: "jsx",
    tags: ["react", "component", "jsx", "basics"],
    notes: "A component is a function that returns what you want on screen. The name must start with a capital letter.",
    codeBlock: "function Greeting() {\n  return <h1>Hello</h1>;\n}\n\n// use it like a tag\n<Greeting />",
    notesAfter: "Lowercase names are treated as plain HTML tags, so <greeting /> will not work.",
  },
  {
    id: 93,
    category: "React",
    subcategory: "Components",
    title: "Pass data in with props",
    language: "jsx",
    tags: ["react", "props", "component", "data", "basics"],
    notes: "Props are values you hand to a component, written like HTML attributes. The component receives them as one object.",
    codeBlock: "function Greeting(props) {\n  return <h1>Hello {props.name}</h1>;\n}\n\n<Greeting name=\"Jane\" />\n// Hello Jane",
    notesAfter: "Props are read-only. A component cannot change the props it was given.",
  },
  {
    id: 94,
    category: "React",
    subcategory: "Components",
    title: "Unpack props straight away",
    language: "jsx",
    tags: ["react", "props", "destructuring", "component", "basics"],
    notes: "Most React code pulls the props apart in the function line. It saves writing props. over and over.",
    codeBlock: "function Greeting({ name, age }) {\n  return <h1>{name} is {age}</h1>;\n}\n\n<Greeting name=\"Jane\" age={30} />\n// Jane is 30",
    notesAfter: "Text goes in quotes. Anything else - numbers, variables, arrays - goes in curly braces.",
  },
  {
    id: 95,
    category: "React",
    subcategory: "Rendering",
    title: "Show a list of things",
    language: "jsx",
    tags: ["react", "list", "map", "key", "render", "basics"],
    notes: "Use map to turn a list of data into a list of elements. Each one needs a key so React can tell them apart.",
    codeBlock: "const fruits = ['apple', 'banana'];\n\nreturn (\n  <ul>\n    {fruits.map(fruit => (\n      <li key={fruit}>{fruit}</li>\n    ))}\n  </ul>\n);",
    notesAfter: "The key should be something that stays the same for that item, like an id. Avoid using the position number.",
  },
  {
    id: 96,
    category: "React",
    subcategory: "Rendering",
    title: "Show something only sometimes",
    language: "jsx",
    tags: ["react", "conditional", "render", "jsx", "basics"],
    notes: "&& shows the thing on the right only when the left side is true.",
    codeBlock: "{isLoading && <Spinner />}\n\n{error && <p>{error.message}</p>}",
    notesAfter: "Careful with numbers: {count && <List />} prints a literal 0 when count is 0. Write {count > 0 && ...} instead.",
  },
  {
    id: 97,
    category: "React",
    subcategory: "Rendering",
    title: "Choose between two things",
    language: "jsx",
    tags: ["react", "ternary", "conditional", "jsx", "basics"],
    notes: "A question mark picks one of two things to show.",
    codeBlock: "{isLoading\n  ? <Spinner />\n  : <NotesList notes={notes} />\n}",
  },
  {
    id: 98,
    category: "React",
    subcategory: "State",
    title: "Remember a value with useState",
    language: "javascript",
    tags: ["react", "usestate", "state", "hook", "basics"],
    notes: "useState gives you two things: the current value, and a function to change it. Changing it makes the component redraw.",
    codeBlock: "const [count, setCount] = useState(0);\n\n// read it\nconsole.log(count);\n\n// change it\nsetCount(1);",
    notesAfter: "The value in the brackets, useState(0), is only the starting value. It is ignored after the first render.",
  },
  {
    id: 99,
    category: "React",
    subcategory: "State",
    title: "Update state based on the old value",
    language: "javascript",
    tags: ["react", "state", "updater", "previous", "basics"],
    notes: "When the new value depends on the old one, pass a function. React hands you the latest value.",
    codeBlock: "const [count, setCount] = useState(0);\n\nsetCount(prev => prev + 1);",
    notesAfter: "Writing setCount(count + 1) usually works, but breaks if you call it twice in a row. The function form is always safe.",
  },
  {
    id: 100,
    category: "React",
    subcategory: "State",
    title: "Keep an object in state",
    language: "javascript",
    tags: ["react", "state", "object", "form", "spread", "basics"],
    notes: "Never change the object directly. Make a copy with the three dots and change the copy.",
    codeBlock: "const [form, setForm] = useState({ name: '', email: '' });\n\nsetForm(prev => ({ ...prev, name: 'Jane' }));",
    notesAfter: "The extra brackets around { ...prev } are needed, otherwise JavaScript reads the curly braces as a code block.",
  },
  {
    id: 101,
    category: "React",
    subcategory: "State",
    title: "Add an item to a list in state",
    language: "javascript",
    tags: ["react", "state", "array", "add", "spread", "basics"],
    notes: "Same idea as objects: build a new array rather than pushing onto the old one.",
    codeBlock: "const [items, setItems] = useState([]);\n\nsetItems(prev => [...prev, 'new item']);",
    notesAfter: "push would change the existing array, and React would not notice anything had changed.",
  },
  {
    id: 102,
    category: "React",
    subcategory: "Forms",
    title: "Connect an input to state",
    language: "jsx",
    tags: ["react", "form", "input", "controlled", "onchange", "basics"],
    notes: "Give the input a value from state and an onChange that updates it. This is called a controlled input.",
    codeBlock: "const [name, setName] = useState('');\n\n<input\n  value={name}\n  onChange={event => setName(event.target.value)}\n/>",
    notesAfter: "event.target.value is whatever is currently typed in the box.",
  },
  {
    id: 103,
    category: "React",
    subcategory: "Forms",
    title: "Handle many inputs with one function",
    language: "jsx",
    tags: ["react", "form", "input", "handler", "name", "basics"],
    notes: "Give each input a name that matches its key in state. Then one handler can update any of them.",
    codeBlock: "function handleChange(event) {\n  const { name, value } = event.target;\n  setForm(prev => ({ ...prev, [name]: value }));\n}\n\n<input name=\"title\" value={form.title} onChange={handleChange} />\n<input name=\"email\" value={form.email} onChange={handleChange} />",
    notesAfter: "The square brackets around [name] mean 'use the value of the name variable as the key'.",
  },
  {
    id: 104,
    category: "React",
    subcategory: "Forms",
    title: "Stop a form reloading the page",
    language: "jsx",
    tags: ["react", "form", "submit", "preventdefault", "basics"],
    notes: "By default a form submit reloads the whole page. preventDefault stops that.",
    codeBlock: "function handleSubmit(event) {\n  event.preventDefault();\n  console.log('submitted');\n}\n\n<form onSubmit={handleSubmit}>\n  <button type=\"submit\">Save</button>\n</form>",
    notesAfter: "If your page flashes and clears itself on submit, a missing preventDefault is almost always why.",
  },
  {
    id: 105,
    category: "React",
    subcategory: "Effects",
    title: "Run code after the component appears",
    language: "javascript",
    tags: ["react", "useeffect", "hook", "mount", "basics"],
    notes: "useEffect runs code after the component is drawn. The empty brackets at the end mean 'only once, when it first appears'.",
    codeBlock: "useEffect(() => {\n  console.log('component appeared');\n}, []);",
    notesAfter: "Those brackets at the end are the dependency list. Empty means run once.",
  },
  {
    id: 106,
    category: "React",
    subcategory: "Effects",
    title: "Run code when a value changes",
    language: "javascript",
    tags: ["react", "useeffect", "dependency", "watch", "basics"],
    notes: "Put a value in the dependency list and the effect runs again whenever that value changes.",
    codeBlock: "useEffect(() => {\n  document.title = 'Count: ' + count;\n}, [count]);",
    notesAfter: "Leave the list out completely and the effect runs after every single render, which is usually a mistake.",
  },
  {
    id: 107,
    category: "React",
    subcategory: "Effects",
    title: "Clean up after an effect",
    language: "javascript",
    tags: ["react", "useeffect", "cleanup", "timer", "basics"],
    notes: "If your effect starts something ongoing, return a function that stops it. React runs it when the component goes away.",
    codeBlock: "useEffect(() => {\n  const timer = setInterval(tick, 1000);\n\n  return () => {\n    clearInterval(timer);\n  };\n}, []);",
    notesAfter: "Without the cleanup the timer keeps running after the component is gone.",
  },
  {
    id: 108,
    category: "React",
    subcategory: "Storage",
    title: "Load saved data into state",
    language: "javascript",
    tags: ["react", "localstorage", "usestate", "initial", "lazy", "basics"],
    notes: "Pass a function to useState and React runs it once, on the first render only. That makes it the right place to read localStorage.",
    codeBlock: "const [theme, setTheme] = useState(() => {\n  return localStorage.getItem('theme') || 'light';\n});",
    notesAfter: "Write useState(localStorage.getItem('theme')) without the function and it reads storage on every single render, which is wasted work.",
  },
  {
    id: 109,
    category: "React",
    subcategory: "Storage",
    title: "Save state whenever it changes",
    language: "javascript",
    tags: ["react", "localstorage", "useeffect", "save", "persist", "basics"],
    notes: "Put the value in a useEffect dependency list. The effect runs every time it changes, saving the new value.",
    codeBlock: "const [theme, setTheme] = useState('light');\n\nuseEffect(() => {\n  localStorage.setItem('theme', theme);\n}, [theme]);",
    notesAfter: "Do not call setItem inside your click handlers. One effect covers every way the value might change.",
  },
  {
    id: 110,
    category: "React",
    subcategory: "Storage",
    title: "Save a list from state",
    language: "javascript",
    tags: ["react", "localstorage", "array", "json", "persist", "favourites"],
    notes: "Same pattern as a single value, with JSON.stringify to turn the list into text.",
    codeBlock: "const [favourites, setFavourites] = useState(() => {\n  const saved = localStorage.getItem('favourites');\n  return saved ? JSON.parse(saved) : [];\n});\n\nuseEffect(() => {\n  localStorage.setItem('favourites', JSON.stringify(favourites));\n}, [favourites]);",
    notesAfter: "Read once when the component appears, write every time the list changes.",
  },
  {
    id: 111,
    category: "React",
    subcategory: "Storage",
    title: "Put it in a reusable hook",
    language: "javascript",
    tags: ["react", "localstorage", "hook", "custom hook", "reuse"],
    notes: "Wrapping the pattern in your own hook means you only write it once, then use it like useState anywhere.",
    codeBlock: "function useStoredState(key, startingValue) {\n  const [value, setValue] = useState(() => {\n    const saved = localStorage.getItem(key);\n    return saved ? JSON.parse(saved) : startingValue;\n  });\n\n  useEffect(() => {\n    localStorage.setItem(key, JSON.stringify(value));\n  }, [key, value]);\n\n  return [value, setValue];\n}\n\n// use it exactly like useState\nconst [theme, setTheme] = useStoredState('theme', 'light');",
    notesAfter: "A custom hook is just a function whose name starts with 'use' and which calls other hooks inside.",
  },
  {
    id: 112,
    category: "React",
    subcategory: "Storage",
    title: "Never read storage during render",
    language: "javascript",
    tags: ["react", "localstorage", "render", "gotcha", "hydration"],
    notes: "Reading localStorage directly in the body of a component runs on every render and breaks server rendering. Read it in useState or useEffect instead.",
    codeBlock: "// wrong - runs every render\nfunction Page() {\n  const theme = localStorage.getItem('theme');\n  return <div className={theme} />;\n}\n\n// right - runs once\nfunction Page() {\n  const [theme] = useState(() => localStorage.getItem('theme'));\n  return <div className={theme} />;\n}",
    notesAfter: "If you ever move to Next.js, the wrong version crashes outright, because there is no localStorage on the server.",
  },

  // ── React Query ─────────────────────────────────────────────────────────
  {
    id: 113,
    category: "React Query",
    subcategory: "Queries",
    title: "Fetch data with useQuery",
    language: "javascript",
    tags: ["react query", "tanstack", "usequery", "fetch", "basics"],
    notes: "useQuery handles loading, errors and caching for you. queryKey names the data, queryFn says how to get it.",
    codeBlock: "const { data, isLoading, isError } = useQuery({\n  queryKey: ['notes'],\n  queryFn: fetchNotes,\n});",
    notesAfter: "Give queryFn the function name with no brackets. Writing fetchNotes() calls it immediately, which is wrong.",
  },
  {
    id: 114,
    category: "React Query",
    subcategory: "Queries",
    title: "Show loading and error states",
    language: "javascript",
    tags: ["react query", "loading", "error", "state", "basics"],
    notes: "useQuery tells you which state you are in, so you can show the right thing.",
    codeBlock: "const { data, isLoading, isError, error } = useQuery({\n  queryKey: ['notes'],\n  queryFn: fetchNotes,\n});\n\nif (isLoading) return <Spinner />;\nif (isError) return <p>{error.message}</p>;\n\nreturn <NotesList notes={data} />;",
    notesAfter: "Use error.message, not error on its own. React cannot display an Error object and will throw.",
  },
  {
    id: 115,
    category: "React Query",
    subcategory: "Queries",
    title: "Pass a value into the fetch",
    language: "javascript",
    tags: ["react query", "querykey", "parameter", "cache", "basics"],
    notes: "When the fetch depends on a value, wrap it in an arrow function and add that value to the key.",
    codeBlock: "const { data } = useQuery({\n  queryKey: ['notes', category],\n  queryFn: () => fetchNotes(category),\n});",
    notesAfter: "Putting category in the key means each category gets cached separately, instead of overwriting each other.",
  },
  {
    id: 116,
    category: "React Query",
    subcategory: "Mutations",
    title: "Send data with useMutation",
    language: "javascript",
    tags: ["react query", "usemutation", "post", "save", "basics"],
    notes: "useMutation is for changing data. Call mutate with what you want to send.",
    codeBlock: "const { mutate, isPending } = useMutation({\n  mutationFn: createNote,\n});\n\nmutate({ title: 'New note' });",
    notesAfter: "Note the name is mutationFn here, not queryFn.",
  },
  {
    id: 117,
    category: "React Query",
    subcategory: "Mutations",
    title: "Refresh the list after saving",
    language: "javascript",
    tags: ["react query", "invalidate", "refetch", "cache", "basics"],
    notes: "After a save, tell React Query the old data is out of date. It fetches fresh data automatically.",
    codeBlock: "const queryClient = useQueryClient();\n\nconst { mutate } = useMutation({\n  mutationFn: createNote,\n  onSuccess: () => {\n    queryClient.invalidateQueries({ queryKey: ['notes'] });\n  },\n});",
    notesAfter: "Without this, you save something new and the list on screen does not update.",
  },

  // ── Git ─────────────────────────────────────────────────────────────────
  {
    id: 118,
    category: "Git",
    subcategory: "Setup",
    title: "Tell Git who you are",
    language: "bash",
    tags: ["git", "config", "setup", "name", "email", "basics"],
    notes: "Git puts your name and email on every commit. Set this once and forget about it.",
    codeBlock: "git config --global user.name \"Your Name\"\ngit config --global user.email \"you@example.com\"\n\n# check what is set\ngit config --global --list",
  },
  {
    id: 119,
    category: "Git",
    subcategory: "Setup",
    title: "Start tracking a project",
    language: "bash",
    tags: ["git", "init", "start", "repository", "basics"],
    notes: "Run this inside your project folder. It creates a hidden .git folder where Git keeps its history.",
    codeBlock: "cd my-project\ngit init",
    notesAfter: "You only do this once per project.",
  },
  {
    id: 120,
    category: "Git",
    subcategory: "Setup",
    title: "Download an existing project",
    language: "bash",
    tags: ["git", "clone", "download", "copy", "basics"],
    notes: "clone copies a project from GitHub onto your machine, history and all.",
    codeBlock: "git clone https://github.com/user/repo.git\n\n# it creates a folder named after the repo\ncd repo",
  },
  {
    id: 121,
    category: "Git",
    subcategory: "Everyday",
    title: "See what you have changed",
    language: "bash",
    tags: ["git", "status", "check", "changes", "basics"],
    notes: "status is the command you run most. It tells you which files changed and what Git plans to do next.",
    codeBlock: "git status",
    notesAfter: "When you are unsure what is going on, run this first.",
  },
  {
    id: 122,
    category: "Git",
    subcategory: "Everyday",
    title: "Save your work in three steps",
    language: "bash",
    tags: ["git", "add", "commit", "push", "save", "basics", "workflow"],
    notes: "This is the normal cycle: pick the files, save them with a message, then send them to GitHub.",
    codeBlock: "git add .\ngit commit -m \"Add search filter\"\ngit push",
    notesAfter: "git add . means 'all my changed files'. The message should say what you did, not how.",
  },
  {
    id: 123,
    category: "Git",
    subcategory: "Everyday",
    title: "Get the latest changes",
    language: "bash",
    tags: ["git", "pull", "update", "sync", "basics"],
    notes: "pull downloads what other people have pushed and merges it into your copy.",
    codeBlock: "git pull",
    notesAfter: "Do this before you start working, so you are building on the newest version.",
  },
  {
    id: 124,
    category: "Git",
    subcategory: "Everyday",
    title: "See your recent commits",
    language: "bash",
    tags: ["git", "log", "history", "commits", "basics"],
    notes: "log lists the commit history, newest first. The --oneline flag makes it much easier to scan.",
    codeBlock: "git log --oneline\n\n# a1b2c3d Add search filter\n# f4e5d6c Fix typo in header",
  },
  {
    id: 125,
    category: "Git",
    subcategory: "Branches",
    title: "What a branch is for",
    language: "bash",
    tags: ["git", "branch", "list", "basics"],
    notes: "A branch is a separate line of work. You make one so your half-finished changes do not disturb the main version.",
    codeBlock: "git branch\n\n# * main\n#   feature/search",
    notesAfter: "The star shows which branch you are on right now.",
  },
  {
    id: 126,
    category: "Git",
    subcategory: "Branches",
    title: "Make a new branch and switch to it",
    language: "bash",
    tags: ["git", "branch", "switch", "create", "checkout", "basics"],
    notes: "The -c flag means create. Without it, switch moves to a branch that already exists.",
    codeBlock: "git switch -c feature/search\n\n# later, go back\ngit switch main",
    notesAfter: "You may see git checkout -b in older guides. It does the same thing.",
  },
  {
    id: 127,
    category: "Git",
    subcategory: "Branches",
    title: "Bring a branch into main",
    language: "bash",
    tags: ["git", "merge", "branch", "combine", "basics"],
    notes: "Switch to the branch you want to merge into, then merge the other one in.",
    codeBlock: "git switch main\ngit merge feature/search",
    notesAfter: "Order matters. You are always merging INTO the branch you are standing on.",
  },
  {
    id: 128,
    category: "Git",
    subcategory: "Branches",
    title: "Delete a branch you are done with",
    language: "bash",
    tags: ["git", "branch", "delete", "cleanup", "basics"],
    notes: "Once a branch is merged, you can safely remove it.",
    codeBlock: "git branch -d feature/search\n\n# also remove it from GitHub\ngit push origin --delete feature/search",
    notesAfter: "Git refuses to delete a branch with unmerged work, which is a useful safety net.",
  },
  {
    id: 129,
    category: "Git",
    subcategory: "Undo",
    title: "Throw away changes to a file",
    language: "bash",
    tags: ["git", "restore", "undo", "discard", "basics"],
    notes: "This wipes your edits to that file and puts it back how it was at the last commit.",
    codeBlock: "git restore file.js",
    notesAfter: "There is no undo for this one. The changes are gone.",
  },
  {
    id: 130,
    category: "Git",
    subcategory: "Undo",
    title: "Unstage a file you added by mistake",
    language: "bash",
    tags: ["git", "restore", "unstage", "add", "basics"],
    notes: "This takes the file out of the staging area but keeps your edits.",
    codeBlock: "git restore --staged file.js",
  },
  {
    id: 131,
    category: "Git",
    subcategory: "Undo",
    title: "Undo your last commit but keep the work",
    language: "bash",
    tags: ["git", "reset", "undo", "commit", "soft", "basics"],
    notes: "This removes the commit and puts the changes back as if you had not committed yet.",
    codeBlock: "git reset --soft HEAD~1",
    notesAfter: "HEAD~1 means 'one commit before where I am now'.",
  },
  {
    id: 132,
    category: "Git",
    subcategory: "Undo",
    title: "Undo a commit that is already pushed",
    language: "bash",
    tags: ["git", "revert", "undo", "safe", "pushed", "basics"],
    notes: "revert makes a NEW commit that cancels out an old one. Safe to use on work others already have.",
    codeBlock: "git revert a1b2c3d",
    notesAfter: "Use this instead of reset once a commit is on GitHub. Reset would rewrite history and cause problems for everyone else.",
  },
  {
    id: 133,
    category: "Git",
    subcategory: "Undo",
    title: "Rescue work you thought you lost",
    language: "bash",
    tags: ["git", "reflog", "recover", "lost", "undo"],
    notes: "reflog lists everywhere you have been, including commits that seem to have vanished after a bad reset.",
    codeBlock: "git reflog\n\n# find the commit you want, then\ngit reset --hard a1b2c3d",
    notesAfter: "This has saved a lot of people. If something disappeared, look here before panicking.",
  },
  {
    id: 134,
    category: "Git",
    subcategory: "Undo",
    title: "Put your work aside for a moment",
    language: "bash",
    tags: ["git", "stash", "temporary", "save", "basics"],
    notes: "stash shelves your uncommitted changes so you can switch branches with a clean slate.",
    codeBlock: "git stash\n\n# do something else, then bring it back\ngit stash pop",
  },
  {
    id: 135,
    category: "Git",
    subcategory: "Conflicts",
    title: "What a merge conflict looks like",
    language: "bash",
    tags: ["git", "conflict", "merge", "resolve", "basics"],
    notes: "When two people change the same lines, Git cannot choose. It writes both versions into the file with markers.",
    codeBlock: "<<<<<<< HEAD\nyour version of the line\n=======\ntheir version of the line\n>>>>>>> feature/search",
    notesAfter: "Delete the markers and the version you do not want, leaving the file how it should look.",
  },
  {
    id: 136,
    category: "Git",
    subcategory: "Conflicts",
    title: "Finish a conflict once you have fixed it",
    language: "bash",
    tags: ["git", "conflict", "merge", "continue", "add", "basics"],
    notes: "After editing the file, add it to tell Git it is sorted, then finish the merge.",
    codeBlock: "git add file.js\ngit merge --continue\n\n# or back out entirely\ngit merge --abort",
  },
  {
    id: 137,
    category: "Git",
    subcategory: "Ignoring",
    title: "Stop Git tracking certain files",
    language: "bash",
    tags: ["git", "gitignore", "ignore", "node_modules", "env", "basics"],
    notes: "Put file names or folder names in a .gitignore file and Git will leave them alone.",
    codeBlock: "# .gitignore\nnode_modules\ndist\n.env",
    notesAfter: "Always ignore node_modules and anything with passwords or keys in it.",
  },
  {
    id: 138,
    category: "Git",
    subcategory: "Ignoring",
    title: "Untrack a file you already committed",
    language: "bash",
    tags: ["git", "rm", "cached", "untrack", "gitignore", "gotcha"],
    notes: "Adding to .gitignore does nothing if Git is already tracking the file. You have to remove it first.",
    codeBlock: "git rm --cached .env\ngit commit -m \"Stop tracking .env\"",
    notesAfter: "The --cached flag means 'stop tracking it but leave it on my computer'.",
  },

  // ── GitHub ──────────────────────────────────────────────────────────────
  {
    id: 139,
    category: "GitHub",
    subcategory: "Remotes",
    title: "Connect your project to GitHub",
    language: "bash",
    tags: ["github", "remote", "origin", "push", "basics"],
    notes: "Make an empty repo on GitHub first, then point your local project at it.",
    codeBlock: "git remote add origin https://github.com/user/repo.git\ngit push -u origin main",
    notesAfter: "The -u part only matters the first time. After that, plain git push works.",
  },
  {
    id: 140,
    category: "GitHub",
    subcategory: "Remotes",
    title: "See where your project points",
    language: "bash",
    tags: ["github", "remote", "origin", "url", "check"],
    notes: "This shows the GitHub address your project is linked to.",
    codeBlock: "git remote -v\n\n# origin  https://github.com/user/repo.git (fetch)\n# origin  https://github.com/user/repo.git (push)",
  },
  {
    id: 141,
    category: "GitHub",
    subcategory: "Pull Requests",
    title: "Open a pull request",
    language: "bash",
    tags: ["github", "pull request", "pr", "gh", "review", "basics"],
    notes: "A pull request asks for your branch to be merged, and gives people a place to review it first.",
    codeBlock: "git push -u origin feature/search\n\n# then, with the GitHub CLI\ngh pr create --fill",
    notesAfter: "--fill uses your branch name and commit messages for the title and description.",
  },
  {
    id: 142,
    category: "GitHub",
    subcategory: "Pull Requests",
    title: "Check out someone else's pull request",
    language: "bash",
    tags: ["github", "pull request", "pr", "checkout", "review"],
    notes: "This pulls their branch onto your machine so you can run it and see it working.",
    codeBlock: "gh pr checkout 42",
  },
  {
    id: 143,
    category: "GitHub",
    subcategory: "Issues",
    title: "Close an issue from a commit",
    language: "bash",
    tags: ["github", "issue", "close", "fixes", "commit"],
    notes: "Put 'Fixes' and the issue number in your commit message. GitHub closes it when the commit reaches the main branch.",
    codeBlock: "git commit -m \"Fix search crash\n\nFixes #12\"",
  },
  {
    id: 144,
    category: "GitHub",
    subcategory: "Auth",
    title: "Set up SSH so you stop typing passwords",
    language: "bash",
    tags: ["github", "ssh", "key", "auth", "password", "basics"],
    notes: "Make a key, paste the public half into GitHub settings, then test it.",
    codeBlock: "ssh-keygen -t ed25519 -C \"you@example.com\"\n\n# print the public key and copy it\ncat ~/.ssh/id_ed25519.pub\n\n# test the connection\nssh -T git@github.com",
    notesAfter: "Only ever share the .pub file. The other one is private.",
  },

  // ── CSS ─────────────────────────────────────────────────────────────────
  {
    id: 145,
    category: "CSS",
    subcategory: "Layout",
    title: "Put things in a row",
    language: "css",
    tags: ["css", "flexbox", "flex", "row", "layout", "basics"],
    notes: "display: flex puts children side by side. gap adds space between them.",
    codeBlock: ".row {\n  display: flex;\n  gap: 1rem;\n}",
    notesAfter: "This is the most useful two lines in CSS layout.",
  },
  {
    id: 146,
    category: "CSS",
    subcategory: "Layout",
    title: "Centre something with flexbox",
    language: "css",
    tags: ["css", "flexbox", "center", "align", "justify", "basics"],
    notes: "justify-content handles left to right. align-items handles top to bottom.",
    codeBlock: ".centered {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}",
    notesAfter: "If you switch to flex-direction: column, those two swap jobs.",
  },
  {
    id: 147,
    category: "CSS",
    subcategory: "Layout",
    title: "Stack things in a column",
    language: "css",
    tags: ["css", "flexbox", "column", "stack", "vertical", "basics"],
    notes: "Add flex-direction: column and the children stack downwards instead of across.",
    codeBlock: ".stack {\n  display: flex;\n  flex-direction: column;\n  gap: 1rem;\n}",
  },
  {
    id: 148,
    category: "CSS",
    subcategory: "Layout",
    title: "Make a responsive grid",
    language: "css",
    tags: ["css", "grid", "responsive", "columns", "auto-fit"],
    notes: "This fits as many columns as will fit, each at least 250px wide, and wraps automatically.",
    codeBlock: ".cards {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n  gap: 1rem;\n}",
    notesAfter: "No media queries needed. The browser works out the column count for you.",
  },
  {
    id: 149,
    category: "CSS",
    subcategory: "Sizing",
    title: "Understand rem",
    language: "css",
    tags: ["css", "rem", "units", "size", "font", "basics"],
    notes: "1rem is the browser's base font size, normally 16px. Using rem means your layout scales if someone changes that setting.",
    codeBlock: ".box {\n  padding: 1rem;    /* 16px */\n  font-size: 1.5rem; /* 24px */\n}",
  },
  {
    id: 150,
    category: "CSS",
    subcategory: "Sizing",
    title: "Stop an image overflowing",
    language: "css",
    tags: ["css", "image", "responsive", "max-width", "basics"],
    notes: "These two lines keep an image inside its container no matter how big the file is.",
    codeBlock: "img {\n  max-width: 100%;\n  height: auto;\n}",
  },

  // ── Django ──────────────────────────────────────────────────────────────
  {
    id: 151,
    category: "Django",
    subcategory: "Setup",
    title: "Start a Django project",
    language: "bash",
    tags: ["django", "start", "project", "app", "basics"],
    notes: "A project holds the settings. Apps hold the actual features.",
    codeBlock: "django-admin startproject mysite\ncd mysite\npython manage.py startapp notes",
  },
  {
    id: 152,
    category: "Django",
    subcategory: "Setup",
    title: "Run the development server",
    language: "bash",
    tags: ["django", "runserver", "start", "local", "basics"],
    notes: "This starts a local server so you can see your site in a browser.",
    codeBlock: "python manage.py runserver\n\n# then open http://127.0.0.1:8000",
  },
  {
    id: 153,
    category: "Django",
    subcategory: "Models",
    title: "Write a model",
    language: "python",
    tags: ["django", "model", "database", "table", "basics"],
    notes: "A model describes one table in your database. Each attribute becomes a column.",
    codeBlock: "from django.db import models\n\nclass Note(models.Model):\n    title = models.CharField(max_length=200)\n    body = models.TextField()\n    created = models.DateTimeField(auto_now_add=True)",
    notesAfter: "CharField needs a max_length. TextField does not, so use it for longer writing.",
  },
  {
    id: 154,
    category: "Django",
    subcategory: "Models",
    title: "Apply model changes to the database",
    language: "bash",
    tags: ["django", "migration", "makemigrations", "migrate", "basics"],
    notes: "Two steps: write down what changed, then apply it. You do this every time you edit a model.",
    codeBlock: "python manage.py makemigrations\npython manage.py migrate",
    notesAfter: "Commit the migration files to Git. They are part of your project's history.",
  },
  {
    id: 155,
    category: "Django",
    subcategory: "ORM",
    title: "Get records out of the database",
    language: "python",
    tags: ["django", "orm", "query", "filter", "get", "basics"],
    notes: "all gives you everything, filter narrows it down, get fetches exactly one.",
    codeBlock: "Note.objects.all()\n\nNote.objects.filter(category='React')\n\nNote.objects.get(id=1)",
    notesAfter: "get raises an error if it finds none or more than one. filter just gives you an empty list.",
  },
  {
    id: 156,
    category: "Django",
    subcategory: "ORM",
    title: "Create and save a record",
    language: "python",
    tags: ["django", "orm", "create", "save", "basics"],
    notes: "create makes it and saves it in one go.",
    codeBlock: "note = Note.objects.create(\n    title='Hello',\n    body='My first note',\n)\n\nprint(note.id)\n# 1",
  },
]
